nome=input("Digite um Funcionário: ")
empresa=input("Digite o nome da empresa: ")
qtde_funcionario=int(input("Quantidade de Funcionários: "))
mediaMensalidade=float(input("Digite a Média de Mensalidade: "))
print(nome = " trabalha na empresa " + empresa)
print("Possui: ", qtde_funcionario, " funcionários.")
print("++++++++++++++++++++Verifique os Dados Abaixo++++++++++++++++++++++")
print("o tipo de dado da variavel [nome] é: ", type(nome))
print("o tipo de dado da variavel [empresa] é: ", type(empresa))
print("o tipo de dado da variavel [qtde_funcionario] é: ", type(qtde_funcionario))
print("o tipo de dado da variavel [mediaMensalidade] é: ", type(mediaMensalidade))